import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// import {Link} from 'react-bootstrap'
import Homepage from '../components/Homepage/Homepage.js';

export default function Home() {
  return (
    <div className={styles.container}>
      	<Head>
        	<title>Yuvasoft Website</title>
        	<meta name="description" content="Generated by create next app" />
        	<link rel="icon" href="/favicon.ico" />
      	</Head>
		  
      	
		<Homepage />
    </div>
  )
}
